---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eeBc
  labels:
    app: eeBc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eeBc
  template:
    metadata:
      labels:
        app: eeBc
    spec:
      containers:
        - name: eeBc
          image: username/eeBc:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaBc
  labels:
    app: aaBc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aaBc
  template:
    metadata:
      labels:
        app: aaBc
    spec:
      containers:
        - name: aaBc
          image: username/aaBc:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbBc
  labels:
    app: bbBc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbBc
  template:
    metadata:
      labels:
        app: bbBc
    spec:
      containers:
        - name: bbBc
          image: username/bbBc:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccBc
  labels:
    app: ccBc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccBc
  template:
    metadata:
      labels:
        app: ccBc
    spec:
      containers:
        - name: ccBc
          image: username/ccBc:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddBc
  labels:
    app: ddBc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddBc
  template:
    metadata:
      labels:
        app: ddBc
    spec:
      containers:
        - name: ddBc
          image: username/ddBc:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: eeBc
  labels:
    app: eeBc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: eeBc


---


apiVersion: v1
kind: Service
metadata:
  name: aaBc
  labels:
    app: aaBc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aaBc


---


apiVersion: v1
kind: Service
metadata:
  name: bbBc
  labels:
    app: bbBc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bbBc


---


apiVersion: v1
kind: Service
metadata:
  name: ccBc
  labels:
    app: ccBc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ccBc


---


apiVersion: v1
kind: Service
metadata:
  name: ddBc
  labels:
    app: ddBc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ddBc

